const config = {
  REACT_APP_PROJECT_STATE: process.env.REACT_APP_PROJECT_STATE,
  REACT_APP_DEVELOPMENT_BACKEND_BASE_URL: process.env.REACT_APP_DEVELOPMENT_BACKEND_BASE_URL, 
  REACT_APP_PRODUCTION_BACKEND_BASE_URL: process.env.REACT_APP_PRODUCTION_BACKEND_BASE_URL,
  REACT_APP_PRODUCTION_BACKEND_WEBSOCKET: process.env.REACT_APP_PRODUCTION_BACKEND_WEBSOCKET,
  REACT_APP_DEVELOPMENT_BACKEND_WEBSOCKET: process.env.REACT_APP_DEVELOPMENT_BACKEND_WEBSOCKET,
  REACT_APP_KEY: process.env.REACT_APP_KEY,
  REACT_APP_MAPBOX_KEY: process.env.REACT_APP_MAPBOX_KEY,
  REACT_APP_SECRET: process.env.REACT_APP_SECRET
};

export default config;